version: '3.8'

services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=256M --max-connections=100
    volumes:
      - "./volumes/database:/var/lib/mysql"
    environment:
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
    networks:
      - pterodactyl
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  cache:
    image: redis:7-alpine
    restart: always
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    networks:
      - pterodactyl
    deploy:
      resources:
        limits:
          memory: 160M
        reservations:
          memory: 64M

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
      - cache
    volumes:
      - "./volumes/panel/var/log/pterodactyl:/app/var/log/pterodactyl"
      - "./volumes/panel/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./volumes/panel/nginx/logs:/var/log/nginx"
      - "./volumes/panel/nginx/ssl:/etc/ssl/certs"
      - "./volumes/panel/env:/app/.env"
    environment:
      APP_URL: "${APP_URL}"
      APP_TIMEZONE: "UTC"
      APP_SERVICE_AUTHOR: "${APP_SERVICE_AUTHOR}"
      TRUSTED_PROXIES: "*"
      LE_EMAIL: "${LE_EMAIL}"
    networks:
      - pterodactyl
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 384M

  wings:
    image: ghcr.io/pterodactyl/wings:latest
    restart: always
    networks:
      - pterodactyl
      - wings0
    ports:
      - "8080:8080"
      - "2022:2022"
      - "25565-25575:25565-25575"  # Multiple Minecraft server ports
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/tmp/pterodactyl:/tmp/pterodactyl"
      - "./volumes/wings:/etc/pterodactyl"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  pterodactyl:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/16"
  wings0:
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0