version: '3.8'

services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./volumes/database:/var/lib/mysql"
    environment:
      MYSQL_PASSWORD: "CHANGE_ME"
      MYSQL_ROOT_PASSWORD: "CHANGE_ME_TOO"
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
    networks:
      - pterodactyl

  cache:
    image: redis:alpine
    restart: always
    networks:
      - pterodactyl

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
      - cache
    volumes:
      - "./volumes/panel/var/log/pterodactyl:/app/var/log/pterodactyl"
      - "./volumes/panel/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./volumes/panel/nginx/logs:/var/log/nginx"
      - "./volumes/panel/nginx/ssl:/etc/ssl/certs"
    environment:
      APP_NAME: "Pterodactyl"
      APP_ENV: "production"
      APP_DEBUG: "false"
      APP_KEY: "base64:4IOG3KGaUaD1a92x7xAMMd3XiHfuelkZnEf9XUoAkL4="
      APP_URL: "http://localhost"
      APP_TIMEZONE: "UTC"
      APP_SERVICE_AUTHOR: "noreply@example.com"
      DB_HOST: "database"
      DB_PORT: "3306"
      DB_DATABASE: "panel"
      DB_USERNAME: "pterodactyl"
      DB_PASSWORD: "CHANGE_ME"
      REDIS_HOST: "cache"
      REDIS_PASSWORD: ""
      REDIS_PORT: "6379"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      TRUSTED_PROXIES: "*"
      LE_EMAIL: ""
    networks:
      - pterodactyl

  wings:
    image: ghcr.io/pterodactyl/wings:latest
    restart: always
    networks:
      - pterodactyl
      - wings0
    ports:
      - "8080:8080"
      - "2022:2022"
      - "25565:25565"  # Minecraft server port
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/tmp/pterodactyl:/tmp/pterodactyl"
      - "./volumes/wings:/etc/pterodactyl"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true

networks:
  pterodactyl:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/16"
  wings0:
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0