debug: false
uuid: 
token_id: 
token: 
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: 
    key: 
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
allowed_origins: []