# Geyser Configuration File
# https://github.com/GeyserMC/Geyser/wiki/Configuration

bedrock:
  # The IP address that will listen for connections.
  # Generally, you should only uncomment and change this if you want to limit what IPs can connect to your server.
  #address: 0.0.0.0
  # The port that will listen for connections
  port: 19132
  # Some hosting services change your Java port everytime you start the server and require the same port to be used for Bedrock.
  # This option makes the Bedrock port the same as the Java port every time you start the server.
  clone-remote-port: false
  # The MOTD that will be broadcasted to Minecraft: Bedrock Edition clients. This is irrelevant if "passthrough-motd" is set to true
  motd1: "GeyserMC"
  motd2: "Cross-platform Minecraft Server"

remote:
  # The IP address of the remote (Java Edition) server
  address: 127.0.0.1
  # The port of the remote (Java Edition) server
  port: 25565
  # Authentication type. Can be offline, online, or floodgate (see https://github.com/GeyserMC/Geyser/wiki/Floodgate).
  auth-type: floodgate

# Floodgate uses encryption to ensure use from authorised sources.
# This should point to the public key generated by Floodgate (Bungee or CraftBukkit)
# You can ignore this when not using Floodgate.
floodgate-key-file: key.pem

# The Xbox/Minecraft: Bedrock Edition username is the key for the Java server auth-info.
# This allows automatic configuration/login to the remote server.
usernames:
  # Bedrock username: Java username
  # Example: "BedrockUser": "JavaUser"

# Specify how many days X-boxed usernames will be stored in cache.
# When this time is elapsed, the cached username will be deleted and the player will be asked to re-link.
xbox-profile-cache: 7

# Bedrock clients can have usernames up to 16 characters long.
# On Java, usernames have to be 3-16 characters long.
# This setting allows the Geyser to make Bedrock usernames fit.
username-prefix: "."

# Pass the MOTD, player list and/or protocol name from the remote server to Bedrock players.
passthrough-motd: false
passthrough-protocol-name: false
passthrough-player-counts: false

# Ignore the player limit set by the server and accept any number of players.
ignore-player-limits: false

# Allow third party capes to be visible. Currently allowing:
# OptiFine capes, LabyMod capes, 5Zig capes and MinecraftCapes
allow-third-party-capes: true

# Allow third party deadmau5 ears to be visible. Currently allowing:
# MinecraftCapes
allow-third-party-ears: false

# Allow a fake cooldown indicator to be sent. Bedrock players otherwise have no cooldown indicator for items such as shields.
show-cooldown: true

# Controls if coordinates are shown to players.
show-coordinates: true

# The default locale if we dont have the one the client requested. Uncomment to not use the default system language.
default-locale: en_us

# Metrics
metrics:
  # If metrics should be enabled
  enabled: true
  # UUID of server, don't change!
  uuid: generateduuid

# Advanced options - generally you do not need to touch these.

# Geyser updates
auto-update: false

# How many seconds to wait while user authorizes Geyser to access their Microsoft account.
# Users can close the pop-up and Geyser will still listen for a response until the time expires.
pending-authentication-timeout: 120

# For online mode authentication type.
xbox-achievements-enabled: true

# bStats is a stat collection service.
# The data collected is viewable here: https://bstats.org/plugin/server-implementation/GeyserMC
# Full privacy policy: https://bstats.org/privacy-policy
metrics-enabled: true

# ADVANCED OPTIONS - DO NOT TOUCH UNLESS YOU KNOW WHAT YOU ARE DOING!

mtu: 1400
debug-mode: false
general-thread-pool: 32
allow-direct-connection: true

config-version: 4